---
name: Test-Run
version: 0.0100_09
author:
  - 'Shlomi Fish C<< <shlomif@iglu.org.il> >>'
abstract: Run Perl standard test scripts with statistics
license: unknown
requires:
  Class::Accessor: 0
  File::Spec: 0.6
  Scalar::Util: 0
  TAPx::Parser: 0.21
  Test::Harness: 2.53
generated_by: Module::Build version 0.2805
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
provides:
  Test::Run::Assert:
    file: lib/Test/Run/Assert.pm
    version: 0.02
  Test::Run::Base:
    file: lib/Test/Run/Base.pm
  Test::Run::Base::Struct:
    file: lib/Test/Run/Base.pm
  Test::Run::Iface:
    file: lib/Test/Run/Iface.pm
  Test::Run::Iterator:
    file: lib/Test/Run/Iterator.pm
    version: 0.02
  Test::Run::Iterator::ARRAY:
    file: lib/Test/Run/Iterator.pm
  Test::Run::Iterator::FH:
    file: lib/Test/Run/Iterator.pm
  Test::Run::Obj:
    file: lib/Test/Run/Obj.pm
    version: 0.0100_09
  Test::Run::Obj::CanonFailedObj:
    file: lib/Test/Run/Obj/Structs.pm
  Test::Run::Obj::Error:
    file: lib/Test/Run/Obj/Error.pm
  Test::Run::Obj::Error::TestsFail:
    file: lib/Test/Run/Obj/Error.pm
  Test::Run::Obj::Error::TestsFail::NoOutput:
    file: lib/Test/Run/Obj/Error.pm
  Test::Run::Obj::Error::TestsFail::NoTestsRun:
    file: lib/Test/Run/Obj/Error.pm
  Test::Run::Obj::Error::TestsFail::Other:
    file: lib/Test/Run/Obj/Error.pm
  Test::Run::Obj::FailedObj:
    file: lib/Test/Run/Obj/Structs.pm
  Test::Run::Obj::TestObj:
    file: lib/Test/Run/Obj/Structs.pm
  Test::Run::Obj::TotObj:
    file: lib/Test/Run/Obj/Structs.pm
  Test::Run::Output:
    file: lib/Test/Run/Output.pm
  Test::Run::Straps:
    file: lib/Test/Run/Straps.pm
    version: 0.24
  Test::Run::Straps::StrapsDetailsObj:
    file: lib/Test/Run/Obj/Structs.pm
  Test::Run::Straps::StrapsTotalsObj:
    file: lib/Test/Run/Obj/Structs.pm
