---
name: Test-Run-TAP-Model
version: 0.06
author:
  - Yuval Kogman <nothingmuch@woobling.org> NUFFIN
  - Max Maischein <corion@cpan.org> CORION
  - James Mastros <james@mastros.biz> JMASTROS
  - Scott McWhirter <scott-cpan@NOSPAMkungfuftr.com> KUNGFUFTR
  - Autrijs Tang <autrijus@autrjius.org> AUTRIJUS
  - Gaal Yahas <gaal@forum2.org> GAAL
abstract: |-
  Accessible (queryable, serializable object) result collector
  for L<Test::Run::Straps> runs.
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  perl: 5.8
build_requires:
  Method::Alias: 0
  Test::More: 0.53
provides:
  Test::Run::TAP::Model:
    file: lib/Test/Run/TAP/Model.pm
    version: 0.06
  Test::Run::TAP::Model::Consolidated:
    file: lib/Test/Run/TAP/Model/Consolidated.pm
  Test::Run::TAP::Model::File:
    file: lib/Test/Run/TAP/Model/File.pm
  Test::Run::TAP::Model::File::Consolidated:
    file: lib/Test/Run/TAP/Model/File/Consolidated.pm
  Test::Run::TAP::Model::Subtest:
    file: lib/Test/Run/TAP/Model/Subtest.pm
generated_by: Module::Build version 0.2704
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
